### ISSUE TITLE
Recently I can't access the website suddenly, why?

### ISSUE THREAD

**Issue by Ethan-cheng521** [lia-univali/cassie#104]

**Comment by AlissonSteffens** [comment]
The team is migrating servers.
@rafaelqg can you help here? (he probably knows the date it will be restablished)

**Comment by rafaelqg** [comment]
Hi @AlissonSteffens  and @Ethan-cheng521  - Now you can access CASSIE here: https://cassiengine.org/.
we are going to enable the https://cassiengine.com in near future.

**Comment by Ethan-cheng521** [comment]
Thank you very much
