### ISSUE TITLE
Error with 1999-09-18 Landsat image

### ISSUE THREAD

**Issue by AlissonSteffens** [lia-univali/cassie#46]
Landsat seems to struggle in finding the right place for this image

![image](https://user-images.githubusercontent.com/6234230/110705074-9eab2c00-81d4-11eb-8660-6a1463d924b5.png)

Image ID is: LANDSAT/LT05/C01/T1_SR/LT05_220079_19990918

The region is the Cabeçuda Beach in Itajaí

**Comment by IsraelEfraim** [comment]
The entire source tile seems to be distorted that way, starting softly south and intensifying as it heads north.

The image ID is LANDSAT/LT05/C01/T1_SR/LT05_220079_19990918 and a sample code can be found in here: https://code.earthengine.google.com/53c96a212dd5292f72ee22547f14aca4

Probably have to remove this tile (or the entire cycle) if we can't get GEE to move it into a Tier 2 Collection.
