### ISSUE TITLE
Help, HelpI am not able to open CAASIE.

### ISSUE THREAD

**Issue by arheem** [lia-univali/cassie#74]
![Picture1](https://user-images.githubusercontent.com/69360729/115382351-18ffa080-a1c4-11eb-85fc-8886ea7a46f6.png)

**Comment by AlissonSteffens** [comment]
Hello @arheem ,

Can you give us more details about the attempt to connect? It seems like a local internet connection filter.
Anyways, you can try to use CASSIE by our develop URL [https://cassie-git-develop-lia-univali.vercel.app/](https://cassie-git-develop-lia-univali.vercel.app/). 

If you are still not able to access it, please let me know.

**Comment by AlissonSteffens** [comment]
I'm closing it right now, for lack of information. If some one can provide us more information about the problem, I may reopen it.
