### ISSUE TITLE
Cassie doesn't remove a baseline when the user cancels it

### ISSUE THREAD

**Issue by AlissonSteffens** [lia-univali/cassie#84]
**Describe the bug**
Although it isn't used, Cassie doesn't remove a baseline when the user cancels it

**To Reproduce**
In the processing page, start making a coastline analysis and then can it while drawing the baseline

**Expected behavior**
The canceled baseline should be deleted

**Screenshots**
![image](https://user-images.githubusercontent.com/6234230/128423875-830060b2-2f03-4db2-b9fd-385ef4741658.png)

**Technical review**
the problem only happens when you cancel the baseline while drawing
![image](https://user-images.githubusercontent.com/6234230/129363724-2ca656eb-8ff2-4cb5-9f01-51a70264b151.png)
If you doubleclick and go to params screen, it will be deleted when you create the next one

**Solution**
The handleAnalyzeCoastline  function 
https://github.com/lia-univali/cassie/blob/4e69f01d143adf40000abab96735998351a9b767/src/store/ducks/imagery/saga/shoreline.js#L199
Is the saga that resolves the Coastline Analises
All overlays made by this function should be placed under the "coastlineData"
https://github.com/lia-univali/cassie/blob/4e69f01d143adf40000abab96735998351a9b767/src/store/ducks/imagery/saga/shoreline.js#L200
Somehow, while in request and wait
https://github.com/lia-univali/cassie/blob/4e69f01d143adf40000abab96735998351a9b767/src/store/ducks/map/saga.js#L19
the function that cancels the drawing is just letting the overlay in the void
It would probably be solved if when canceled, the line was commited to the map (the same way it is when doubleclicked)

**Comment by rafaelqg** [comment]
solved with https://github.com/lia-univali/cassie/pull/87

**Comment by rafaelqg** [comment]
https://github.com/lia-univali/cassie/pull/87
